import 'package:flutter/material.dart';
import 'package:health_bag/globals/myColors.dart';
import 'package:health_bag/globals/myFonts.dart';
import 'package:health_bag/globals/mySpaces.dart';
import 'package:health_bag/widgets/backgrounds/fourthBackground.dart';
import 'package:url_launcher/url_launcher.dart';

const _url = 'mailto:${'support-inr-mi-ayarla@meceware.com'}';

void _launchURL() async =>
    await canLaunch(_url) ? await launch(_url) : throw 'Could not launch $_url';

class PrivacyPolicy extends StatelessWidget {
  static String id = 'privacy-policy';

  String body0 = "\nLast updated: May 10, 2021.\n";

  String body1 =
      "This Privacy Policy describes our policies and procedures on the collection, "
      "use and disclosure of your information when You use the Service and tells "
      "You about your privacy rights and how the law protects You. We use your "
      "Personal data to provide and improve the Service. By using the Service, "
      "You agree to the collection and use of information in accordance with "
      "this Privacy Policy.";

  String body2 =
      "The words of which the initial letter is capitalized have meanings defined "
      "under the following conditions. The following definitions shall have the same "
      "meaning regardless of whether they appear in singular or in plural.";

  String body3 = "For the purpose of our privacy policy:\n";

  List<String> body4 = [
    "Account means a unique account created for You to "
        "access our Service or parts of our Service.",
    "Affiliate means an entity that controls, is controlled "
        "by or is under common control with a party, where 'control' "
        "means ownership of 50% or more of the shares, equity interest or "
        "other securities entitled to vote for election of directors or other managing authority.",
    "Application means the software program provided by the company downloaded "
        "by You on any electronic device, named INR'mi Ayarla",
    'Company (referred to as either "the Company", "We", "Us" or '
        '"Our" in this Agreement) refers to Trabzon SBÜ Ahi Evren '
        'Göğüs Kalp ve Damar Cerrahisi Eğitim ve Araştırma Hastanesi,'
        ' Soğuksu, Vatan Cd. No: 9, 61040 Trabzon Merkez/Trabzon, Turkey.',
    "Country refers to: Turkey",
    "Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
    "Personal Data is any information that relates to an identified or identifiable individual.",
    "Service refers to the Application.",
    "Service Provider means any natural or legal person who processes the data on behalf of the Company. "
        "It refers to third-party companies or individuals employed by the Company to facilitate the Service, "
        "to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.",
    "Usage Data refers to data collected automatically, either generated by the use of the Service or "
        "from the Service infrastructure itself (for example, the duration of a page visit).",
    "You means the individual accessing or using the Service, or the company, or other legal entity on behalf "
        "of which such individual is accessing or using the Service, as applicable."
  ];

  String body5 =
      "While using Our Service, We may ask You to provide Us with certain personally "
      "identifiable information that can be used to contact or identify You. "
      "Personally identifiable information may include, but is not limited to:\n";

  List<String> body6 = [
    "Email address",
    "First name and last name",
    "Phone number",
    "Address, State, Province, ZIP/Postal code, City",
    "Usage Data"
  ];

  String body7 =
      "Usage Data is collected automatically when using the Service.\n\nUsage Data may "
      "include information such as Your Device's Internet Protocol address (e.g. IP address), "
      "browser type, browser version, the pages of our Service that You visit, the time and "
      "date of Your visit, the time spent on those pages, unique device identifiers and other "
      "diagnostic data.\n\nWhen You access the Service by or through a mobile device, We may collect certain "
      "information automatically, including, but not limited to, the type of mobile device You use, "
      "Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, "
      "the type of mobile Internet browser You use, unique device identifiers and other diagnostic "
      "data.\n\nWe may also collect information that Your browser sends whenever You visit our Service or "
      "when You access the Service by or through a mobile device.";

  String body8 =
      "While using Our Application, in order to provide features of Our Application, We may collect, with Your prior "
      "permission:\n\n• Pictures, Documents and other information from your Device Storage\n\nWe use this information to "
      "provide features of Our Service, to improve and customize Our Service. The information may be uploaded "
      "to the Company's servers and/or a Service Provider's server or it may be simply stored on Your "
      "device.\n\nYou can enable or disable access to this information at any time, through Your Device settings.";

  String body9 =
      "The Company may use Personal Data for the following purposes:\n";

  List<String> body10 = [
    "To provide and maintain our Service, including to monitor the usage of our Service.",
    "To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.",
    "For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.",
    "To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.",
    "To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.",
    "To manage Your requests: To attend and manage Your requests to Us.",
    "For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.",
    "For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience."
  ];

  String body11 =
      "The Company will retain Your Personal Data only for as long as is necessary for the "
      "purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent "
      "necessary to comply with our legal obligations (for example, if we are required to retain your data to "
      "comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.\n\nThe "
      "Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for "
      "a shorter period of time, except when this data is used to strengthen the security or to improve the "
      "functionality of Our Service, or We are legally obligated to retain this data for longer time periods.";

  String body12 =
      "Your information, including Personal Data, is processed at the Company's operating offices "
      "and in any other places where the parties involved in the processing are located. It means that this "
      "information may be transferred to — and maintained on — computers located outside of Your state, province, "
      "country or other governmental jurisdiction where the data protection laws may differ than those from "
      "Your jurisdiction.\n\nYour consent to this Privacy Policy followed by Your submission of such information "
      "represents Your agreement to that transfer.\n\nThe Company will take all steps reasonably necessary "
      "to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer "
      "of Your Personal Data will take place to an organization or a country unless there are adequate controls "
      "in place including the security of Your data and other personal information.";

  String body13 =
      "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, "
      "or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, "
      "We cannot guarantee its absolute security.";

  String body14 =
      "Our Service does not address anyone under the age of 13. We do not knowingly collect "
      "personally identifiable information from anyone under the age of 13. If You are a parent or guardian "
      "and You are aware that Your child has provided Us with Personal Data, please contact Us. "
      "If We become aware that We have collected Personal Data from anyone under the age of 13 "
      "without verification of parental consent, We take steps to remove that information from Our servers.\n\nIf "
      "We need to rely on consent as a legal basis for processing Your information and Your country requires consent "
      "from a parent, We may require Your parent's consent before We collect and use that information.";

  String body15 =
      "Our Service may contain links to other websites that are not operated by Us. If You click "
      "on a third party link, You will be directed to that third party's site. We strongly advise You to review "
      "the Privacy Policy of every site You visit.\n\nWe have no control over and assume no responsibility for "
      "the content, privacy policies or practices of any third party sites or services.";

  String body16 =
      "We may update Our Privacy Policy from time to time. We will notify You of any changes by "
      "posting the new Privacy Policy on this page.\n\nWe will let You know via email and/or a prominent notice "
      "on Our Service, prior to the change becoming effective and update the 'Last updated' date at the top of "
      "this Privacy Policy.\n\nYou are advised to review this Privacy Policy periodically for any changes. Changes "
      "to this Privacy Policy are effective when they are posted on this page.";

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Stack(
          children: [
            FourthBackground(),
            Container(
              padding: EdgeInsets.only(
                top: MediaQuery.of(context).size.height * 0.05,
                left: 20,
                right: 20,
              ),
              child: MyFonts().title1('Privacy Policy', MyColors.white),
            ),
            Container(
              padding: EdgeInsets.only(
                top: MediaQuery.of(context).size.height * 0.15,
                left: 20,
                right: 20,
              ),
              child: SingleChildScrollView(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    MyFonts().body(body0, MyColors.gray),
                    MyFonts().body(body1, MyColors.black),
                    MySpaces.vSmallGapInBetween,
                    MyFonts().heading1(
                        'Interpretation and Definitions', MyColors.black),
                    MySpaces.vSmallestGapInBetween,
                    MyFonts().heading2('Interpretation', MyColors.black),
                    MySpaces.vSmallestGapInBetween,
                    MyFonts().body(body2, MyColors.black),
                    MySpaces.vSmallGapInBetween,
                    MyFonts().heading2('Definitions', MyColors.black),
                    MySpaces.vSmallestGapInBetween,
                    MyFonts().body(body3, MyColors.black),
                    for (int i = 0; i < body4.length; i++)
                      Padding(
                        padding: const EdgeInsets.symmetric(vertical: 5),
                        child: MyFonts().body('• ${body4[i]}', MyColors.black),
                      ),
                    MySpaces.vSmallGapInBetween,
                    MyFonts().heading1(
                        'Collecting and Using Your Personal Data',
                        MyColors.black),
                    MySpaces.vSmallestGapInBetween,
                    MyFonts().heading2('Personal Data', MyColors.black),
                    MySpaces.vSmallestGapInBetween,
                    MyFonts().body(body5, MyColors.black),
                    for (int i = 0; i < body6.length; i++)
                      MyFonts().body('• ${body6[i]}', MyColors.black),
                    MySpaces.vSmallGapInBetween,
                    MyFonts().heading2('Usage Data', MyColors.black),
                    MySpaces.vSmallestGapInBetween,
                    MyFonts().body(body7, MyColors.black),
                    MySpaces.vSmallGapInBetween,
                    MyFonts().heading2(
                        'Information Collected while Using the Application',
                        MyColors.black),
                    MySpaces.vSmallestGapInBetween,
                    MyFonts().body(body8, MyColors.black),
                    MySpaces.vSmallGapInBetween,
                    MyFonts()
                        .heading2('Use of Your Personal Data', MyColors.black),
                    MySpaces.vSmallestGapInBetween,
                    MyFonts().body(body9, MyColors.black),
                    for (int i = 0; i < body10.length; i++)
                      Padding(
                        padding: const EdgeInsets.symmetric(vertical: 5),
                        child: MyFonts().body('• ${body10[i]}', MyColors.black),
                      ),
                    MySpaces.vSmallGapInBetween,
                    MyFonts().heading2(
                        'Retention of Your Personal Data', MyColors.black),
                    MySpaces.vSmallestGapInBetween,
                    MyFonts().body(body11, MyColors.black),
                    MySpaces.vSmallGapInBetween,
                    MyFonts().heading2(
                        'Transfer of Your Personal Data', MyColors.black),
                    MySpaces.vSmallestGapInBetween,
                    MyFonts().body(body12, MyColors.black),
                    MySpaces.vSmallGapInBetween,
                    MyFonts().heading2(
                        'Security of Your Personal Data', MyColors.black),
                    MySpaces.vSmallestGapInBetween,
                    MyFonts().body(body13, MyColors.black),
                    MySpaces.vSmallGapInBetween,
                    MyFonts().heading1("Children's Privacy", MyColors.black),
                    MySpaces.vSmallestGapInBetween,
                    MyFonts().body(body14, MyColors.black),
                    MySpaces.vSmallGapInBetween,
                    MyFonts()
                        .heading1("Links to Other Websites", MyColors.black),
                    MySpaces.vSmallestGapInBetween,
                    MyFonts().body(body15, MyColors.black),
                    MySpaces.vSmallGapInBetween,
                    MyFonts()
                        .heading1("Changes to this Privacy Policy", MyColors.black),
                    MySpaces.vSmallestGapInBetween,
                    MyFonts().body(body16, MyColors.black),
                    MySpaces.vSmallGapInBetween,
                    MyFonts()
                        .heading1("Contact Us", MyColors.black),
                    MySpaces.vSmallestGapInBetween,
                    MyFonts().body("If you have any questions about this Privacy Policy, You can contact us:", MyColors.black),
                    GestureDetector(
                      onTap: () {
                        _launchURL();
                      },
                      child: MyFonts().body('support-inr-mi-ayarla@meceware.com', MyColors.blue),
                    ),
                    MySpaces.vLargeGapInBetween,
                    Center(child: MyFonts().caption('App Version - v1.0.0', MyColors.gray)),
                    MySpaces.vGapInBetween,
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
